#!/usr/bin/env bash

opwd=$PWD
cd -- "$(dirname "$(readlink "$0" || echo "$0")")" || exit $?
cd ../tests_backend || exit $?
source ./utils.lib.bash

if (( $# != 1 )); then
    echo >&2 "USAGE: $0 <C source>"
    exit 2
fi
src=$(utils_resolve_relative "$1" "$opwd")

# $1: arithmetic circuit file to patch
fix_ptrs() {
     sed 's/:0x[0-9a-f]*/:POINTER/' -i -- "$1"
}

utils_compile_c_to_bc "$src" || exit $?
utils_run_bc_parser --primary-backend || exit $?

utils_preprocess_for_c_parser "$src" || exit $?
utils_run_c_parser || exit $?

fix_ptrs "$utils_ARCI_FOR_C_FILE" || exit $?
fix_ptrs "$utils_ARCI_FOR_BC_FILE" || exit $?
utils_check_files_equal "$utils_ARCI_FOR_C_FILE" "$utils_ARCI_FOR_BC_FILE" || exit $?

utils_cleanup
