#!/usr/bin/env bash

opwd=$PWD
cd -- "$(dirname "$(readlink "$0" || echo "$0")")" || exit $?

if (( $# != 1 )); then
    echo >&2 "USAGE: $0 <C source>"
    exit 2
fi
case "$1" in
/*) SRC=$1 ;;
*)  SRC=$opwd/$1 ;;
esac
CLANG=( ${CLANG:-clang} )
ISEKAI=( ../isekai )
BC_FILE=test_bitcode.bc
ARCI_BITCODE=test_out_bitcode.arci
ARCI_C=test_out_c.arci
TEMP_SRC=$(tempfile -s .c)

Trace() {
    printf >&2 '>==> %s\n' "$*"
    "$@"
}

green_pad=$'\e[0;42m~~~~~~ \e[0m'
red_pad=$'\e[0;41m~~~~~~ \e[0m'

(
    Trace "${CLANG[@]}" -DISEKAI_C_PARSER=0 -O0 -c -emit-llvm "$SRC" -o "$BC_FILE" || exit $?

    Trace "${ISEKAI[@]}" --progress --arith="$ARCI_BITCODE" "$BC_FILE" || exit $?

    Trace "${CLANG[@]}" -E -DISEKAI_C_PARSER=1 "$SRC" -o "$TEMP_SRC" || exit $?
    sed '/^#/d' -i -- "$TEMP_SRC" || exit $?
    Trace "${ISEKAI[@]}" --arith="$ARCI_C" "$TEMP_SRC" || exit $?

    old=$(wc -l < "$ARCI_C")
    new=$(wc -l < "$ARCI_BITCODE")
    if (( new <= old )); then
        pad=$green_pad
    else
        pad=$red_pad
    fi
    echo >&2 "${pad} Old: $old lines"
    echo >&2 "${pad} New: $new lines"
)
ret=$?

rm -f -- "$BC_FILE" "$TEMP_SRC"
if (( ret == 0 )); then
    rm -f -- "$ARCI_BITCODE" "$ARCI_BITCODE".in "$ARCI_C" "$ARCI_C".in
fi
exit "$ret"
