#!/usr/bin/env bash

set -e
cd -- "$(dirname "$(readlink "$0" || echo "$0")")"

usage() {
    echo >&2 "USAGE: $0 [testcase directory]"
    exit 2
}

case "$#" in
1)
    testcase_dirs=( "$1" )
    ;;
0)
    shopt -s failglob
    testcase_dirs=( testcases/*/ )
    shopt -u failglob
    ;;
*)
    usage
    ;;
esac

shopt -s nullglob

n_ok=0
n_fail=0
n_skip=0
keep_going=$(( KEEP_GOING ))

for d in "${testcase_dirs[@]}"; do
    dirname=${d%/}
    for infile in "$dirname"/*.in; do
        echo >&2 "{{<<==--•• RUNNING ON “$infile” ••--==>>}}"
        rc=0
        ./old-backend-run-test-case "$dirname"/prog.c "$infile" || rc=$?
        if (( rc != 0 && !keep_going )); then
            exit $rc
        fi
        case "$rc" in
        0)      ((++n_ok)) ;;
        44)     ((++n_fail)) ;;
        *)      ((++n_skip)) ;;
        esac
    done
done

echo >&2
echo >&2 '<-------------------------------------------------------------->'
echo >&2
echo >&2 "PASSED:  $n_ok"
echo >&2 "FAILED:  $n_fail"
echo >&2 "SKIPPED: $n_skip"
echo >&2
echo >&2 '<-------------------------------------------------------------->'
