#!/usr/bin/env bash

set -e
SCRIPT_DIR="$(dirname "$(readlink "$0" || echo "$0")")"
REPO_ROOT=$SCRIPT_DIR/..

if (( $# != 2 )); then
    echo >&2 "USAGE: $0 <C source> <.in file>"
    exit 2
fi
SRC=$1
IN_VALUES=$2

CLANG=( clang -O0 -Wall -Wextra )
ISEKAI=( "$REPO_ROOT"/isekai )
BOILERPLATE_GEN=( "$REPO_ROOT"/boilerplate_gen )
JUDGE=( "$SCRIPT_DIR"/judge -w 32 )

NATIVE_BIN=./a.out
ARCI_FILE=arci.arci
OUT_JUDGE=out_judge.txt
OUT_NATIVE=out_native.txt

SRC_COPY=src_copy_.c

cp -- "$SRC" "$SRC_COPY"

Trace() {
    printf >&2 -- '≈≈≈≈≈> %s\n' "$*"
    "$@"
}

{
    cat < "$SRC_COPY"
    Trace "${BOILERPLATE_GEN[@]}" "$SRC_COPY"
} | Trace "${CLANG[@]}" -fsanitize=undefined -x c - -o "$NATIVE_BIN"

cp -- "$IN_VALUES" "$SRC_COPY".in

Trace "${ISEKAI[@]}" --arith="$ARCI_FILE" "$SRC_COPY"

Trace "${JUDGE[@]}" "$ARCI_FILE" > "$OUT_JUDGE"

Trace "$NATIVE_BIN" < "$ARCI_FILE".in > "$OUT_NATIVE"

if ! cmp -- "$OUT_JUDGE" "$OUT_NATIVE"; then
    echo >&2 '[ERROR] OUTPUTS DIFFER!'
    echo >&2
    Trace diff -u "$OUT_JUDGE" "$OUT_NATIVE" || true
    exit 44
fi

echo >&2 '[OK] OUTPUTS ARE EQUAL'
rm -f -- \
    "$NATIVE_BIN" \
    "$SRC_COPY" "$SRC_COPY".in \
    "$ARCI_FILE" "$ARCI_FILE".in \
    "$OUT_JUDGE" "$OUT_NATIVE"
