#!/usr/bin/env bash

set -e
SCRIPT_DIR="$(dirname "$(readlink "$0" || echo "$0")")"
REPO_ROOT=$SCRIPT_DIR/..

if (( $# != 2 )); then
    echo >&2 "USAGE: $0 <C source> <.in file>"
    exit 2
fi
SRC=$1
IN_VALUES=$2

CLANG=( clang -O0 -Wall -Wextra )
ISEKAI=( "$REPO_ROOT"/isekai )
BOILERPLATE_GEN=( "$REPO_ROOT"/boilerplate_gen )
JUDGE=( "$SCRIPT_DIR"/judge )

NATIVE_BIN=./a.out
BC_FILE=bitcode.bc
ARCI_FILE=arci.arci
OUT_JUDGE=out_judge.txt
OUT_NATIVE=out_native.txt

Trace() {
    printf >&2 -- '≈≈≈≈≈> %s\n' "$*"
    "$@"
}

Trace "${CLANG[@]}" -c -emit-llvm "$SRC" -o "$BC_FILE"

{
    cat < "$SRC"
    Trace "${BOILERPLATE_GEN[@]}" "$SRC"
} | Trace "${CLANG[@]}" -fsanitize=undefined -x c - -o "$NATIVE_BIN"

cp -- "$IN_VALUES" "$BC_FILE".in

Trace "${ISEKAI[@]}" --arith="$ARCI_FILE" "$BC_FILE"

Trace "${JUDGE[@]}" "$ARCI_FILE" > "$OUT_JUDGE"

Trace "$NATIVE_BIN" < "$ARCI_FILE".in > "$OUT_NATIVE"

if ! cmp -- "$OUT_JUDGE" "$OUT_NATIVE"; then
    echo >&2 '[ERROR] OUTPUTS DIFFER!'
    echo >&2
    Trace diff -u "$OUT_JUDGE" "$OUT_NATIVE"
    exit 1
fi

echo >&2 '[OK] OUTPUTS ARE EQUAL'
rm -f -- \
    "$NATIVE_BIN" \
    "$BC_FILE" "$BC_FILE".in \
    "$ARCI_FILE" "$ARCI_FILE".in \
    "$OUT_JUDGE" "$OUT_NATIVE"
