#!/usr/bin/env bash

opwd=$PWD
cd -- "$(dirname "$(readlink "$0" || echo "$0")")" || exit $?
cd .. || exit $?
source ./utils.lib.bash || exit $?

if (( $# != 1 )); then
    echo >&2 "USAGE: $0 <C source>"
    exit 2
fi
src=$(utils_resolve_relative "$1" "$opwd") || exit $?

green_pad=$'\e[0;42m~~~~~~ \e[0m'
red_pad=$'\e[0;41m~~~~~~ \e[0m'

utils_compile_c_to_bc "$src" || exit $?
utils_preprocess_for_c_parser "$src" || exit $?
utils_run_c_parser || exit $?
utils_run_bc_parser || exit $?

old=$(wc -l < "$utils_ARCI_FOR_C_FILE") || exit $?
new=$(wc -l < "$utils_ARCI_FOR_BC_FILE") || exit $?
if (( new <= old )); then
    pad=$green_pad
else
    pad=$red_pad
fi
echo >&2 "${pad} Old: $old lines"
echo >&2 "${pad} New: $new lines"

utils_cleanup
